/* Auth UX v2 — password reset flow for Supabase */
(function(){
  const $=s=>document.querySelector(s);
  function showError(msg,ok=false){const box=$('#authError');if(!box)return;box.textContent=msg;box.style.background=ok?'#EEF7F1':'';box.style.color=ok?'#287044':'';box.classList.add('show')}
  function addForgot(){const form=$('#authForm'), submit=$('#authSubmit');if(!form||!submit||$('#forgotPasswordBtn'))return;const b=document.createElement('button');b.type='button';b.id='forgotPasswordBtn';b.className='auth-forgot';b.textContent='שכחתי סיסמה';b.onclick=requestReset;submit.insertAdjacentElement('afterend',b);sync();}
  function sync(){const b=$('#forgotPasswordBtn');if(b)b.hidden=(window.authMode==='signup'||$('#signupTab')?.classList.contains('active'));}
  async function requestReset(){const email=$('#authEmail')?.value.trim();if(!email){showError('הזן את כתובת האימייל שלך ואז לחץ “שכחתי סיסמה”.');$('#authEmail')?.focus();return}if(!window.supabaseClient){showError('איפוס סיסמה זמין לאחר חיבור Supabase.');return}const b=$('#forgotPasswordBtn');b.disabled=true;b.textContent='שולח קישור...';try{const {error}=await window.supabaseClient.auth.resetPasswordForEmail(email,{redirectTo:location.origin+'/?reset_password=1'});if(error)throw error;showError('שלחנו קישור לאיפוס הסיסמה למייל ✓',true)}catch(e){showError('לא הצלחנו לשלוח קישור. בדוק את כתובת האימייל ונסה שוב.')}finally{b.disabled=false;b.textContent='שכחתי סיסמה'}}
  function openReset(){const p=new URLSearchParams(location.search);if(p.get('reset_password')!=='1'&&!location.hash.includes('type=recovery'))return;const form=$('#authForm');if(!form)return;form.innerHTML='<div class="auth-reset"><h3>בחר סיסמה חדשה</h3><p>הזן סיסמה חדשה של לפחות 6 תווים.</p><label for="newPassword">סיסמה חדשה</label><input id="newPassword" type="password" minlength="6" autocomplete="new-password"><label for="newPassword2">אימות סיסמה</label><input id="newPassword2" type="password" minlength="6" autocomplete="new-password"><button type="button" class="primary auth-submit" id="saveNewPassword">שמור סיסמה חדשה</button><div class="auth-error" id="resetError"></div></div>';$('#authTitle').textContent='איפוס סיסמה';$('#authLead').textContent='עוד רגע חוזרים לעבוד';$('.auth-switch')?.setAttribute('hidden','');$('#saveNewPassword').onclick=saveNewPassword;}
  async function saveNewPassword(){const a=$('#newPassword').value,b=$('#newPassword2').value,err=$('#resetError');if(a.length<6){err.textContent='הסיסמה צריכה להכיל לפחות 6 תווים.';err.classList.add('show');return}if(a!==b){err.textContent='הסיסמאות אינן תואמות.';err.classList.add('show');return}const btn=$('#saveNewPassword');btn.disabled=true;btn.textContent='שומר...';try{const {error}=await window.supabaseClient.auth.updateUser({password:a});if(error)throw error;err.textContent='הסיסמה עודכנה בהצלחה ✓';err.style.background='#EEF7F1';err.style.color='#287044';err.classList.add('show');setTimeout(()=>location.href='/',900)}catch(e){err.textContent='לא הצלחנו לעדכן את הסיסמה. פתח שוב את הקישור מהמייל.';err.classList.add('show')}finally{btn.disabled=false;btn.textContent='שמור סיסמה חדשה'}}
  const original=window.setAuthMode;window.setAuthMode=function(mode){const r=original?.apply(this,arguments);setTimeout(sync,0);return r};
  function init(){addForgot();openReset()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,450));else setTimeout(init,450);
})();
