(function(){
  let deferredPrompt=null;
  const isStandalone=()=>window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true;
  function ensureStyle(){if(document.getElementById('pwaInstallStyle'))return;const s=document.createElement('style');s.id='pwaInstallStyle';s.textContent='.pwa-install-btn{border:1px solid rgba(255,255,255,.35);background:#fff;color:#1e2229;border-radius:10px;padding:9px 12px;font:700 13px inherit;cursor:pointer}.pwa-install-btn[hidden]{display:none!important}.pwa-tip{position:fixed;inset:auto 12px 78px 12px;z-index:9999;max-width:440px;margin:auto;background:#fff;color:#1e2229;border:1px solid #dfe3df;border-radius:14px;padding:14px;box-shadow:0 12px 36px rgba(0,0,0,.18);direction:rtl;font-family:inherit}.pwa-tip button{margin-top:10px;width:100%;min-height:42px;border:0;border-radius:9px;background:#1e2229;color:#fff;font-weight:700}';document.head.appendChild(s)}
  function addButton(){if(isStandalone()||document.getElementById('pwaInstallBtn'))return;ensureStyle();const btn=document.createElement('button');btn.id='pwaInstallBtn';btn.type='button';btn.className='pwa-install-btn';btn.textContent='⬇ התקן אפליקציה';btn.hidden=true;btn.addEventListener('click',async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;btn.hidden=true;return;}const isiOS=/iphone|ipad|ipod/i.test(navigator.userAgent);if(isiOS){showTip('באייפון: פתח את תפריט השיתוף בדפדפן ובחר “הוסף למסך הבית”.');}else{showTip('פתח את תפריט הדפדפן ובחר “התקנת אפליקציה” או “הוסף למסך הבית”.');}});const host=document.querySelector('header.topbar .row')||document.querySelector('header.topbar')||document.body;host.appendChild(btn);if(/iphone|ipad|ipod/i.test(navigator.userAgent))btn.hidden=false;}
  function showTip(text){let tip=document.querySelector('.pwa-tip');if(tip)tip.remove();tip=document.createElement('div');tip.className='pwa-tip';tip.innerHTML='<b>התקנת Carpentry Quotes</b><div style="margin-top:6px">'+text+'</div><button type="button">הבנתי</button>';tip.querySelector('button').onclick=()=>tip.remove();document.body.appendChild(tip)}
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;addButton();const btn=document.getElementById('pwaInstallBtn');if(btn)btn.hidden=false;});
  window.addEventListener('appinstalled',()=>{deferredPrompt=null;const btn=document.getElementById('pwaInstallBtn');if(btn)btn.hidden=true;});
  if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',addButton);else addButton();
})();
