/* Carpentry Quotes — carpenter-first UX layer */
(function(){
  let busy=false;
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  function normalizeNavigation(){const labels={quote:['✦','הצעה'],cutlist:['▦','חיתוך'],orders:['◎','לקוחות'],settings:['⚙','העסק']};$$('nav.tabs button[data-tab]').forEach(btn=>{const cfg=labels[btn.dataset.tab];if(!cfg)return;const icon=$('.tab-icon',btn);if(icon)icon.textContent=cfg[0];const spans=$$('span',btn);if(spans.length>1)spans[spans.length-1].textContent=cfg[1]})}
  function hideLegacyInternalCosting(){const terms=['תכנון','ייצור','תקורה'];$$('label,.field,.row2,.cost-row,.setting-row').forEach(el=>{const txt=(el.textContent||'').trim();if(terms.some(t=>txt.includes(t))){const target=el.matches('label')?(el.closest('.row2')||el.parentElement):el;if(target)target.classList.add('hybrid-hide-cost')}})}
  function polishAiCopy(){$$('.ai-box .hint,.ai-box .warn,.ai-status').forEach(el=>{if((el.textContent||'').includes('דיוק'))el.textContent='ה-AI מציע נתונים ראשוניים. יש לאמת מידות לפני שליחת הצעה.'})}
  function addWorkspaceIntro(){const quote=$('#tab-quote');if(!quote||$('.hy-workspace',quote))return;const hero=document.createElement('section');hero.className='hy-workspace';hero.innerHTML=`<div><span class="hy-eyebrow">הצעת מחיר חדשה</span><h2>הצעה מקצועית, בלי להסתבך</h2><p>מתחילים מהלקוח. אחר כך העבודה, הפריטים והמחיר.</p></div><div class="hy-flow"><span class="active">1 <b>לקוח</b></span><span>2 <b>עבודה</b></span><span>3 <b>פריטים</b></span><span>4 <b>מחיר</b></span><span>5 <b>שליחה</b></span></div>`;quote.insertBefore(hero,quote.firstElementChild)}
  function simplifyChrome(){const journey=$('.journey');if(journey)journey.classList.add('hy-legacy-journey');const trust=$('.trust-row');if(trust)trust.classList.add('hy-trust');$$('body *').forEach(el=>{const t=(el.textContent||'').trim();if(el.children.length<4&&/מצב מקומי.*Supabase/.test(t))el.classList.add('hy-hide-dev')})}
  function moveCustomerFirst(){const quote=$('#tab-quote');if(!quote||quote.dataset.hyOrdered)return;const labels=$$('label',quote);const customerLabel=labels.find(l=>/שם לקוח/.test(l.textContent||''));if(!customerLabel)return;const customerPanel=customerLabel.closest('.panel');const grid=$('.grid2',quote);if(customerPanel&&grid&&customerPanel.parentElement===grid){grid.insertBefore(customerPanel,grid.firstElementChild);customerPanel.classList.add('hy-customer-first');quote.dataset.hyOrdered='1'}}
  function collapseAiOnMobile(){if(innerWidth>860)return;$$('.ai-box').forEach(box=>{if(box.dataset.hyCollapsed)return;box.dataset.hyCollapsed='1';box.classList.add('hy-ai-collapsed');const trigger=document.createElement('button');trigger.type='button';trigger.className='hy-ai-trigger';trigger.innerHTML='<span>📷</span><b>צלם את העבודה עם AI</b><small>אופציונלי — אפשר גם למלא ידנית</small>';trigger.addEventListener('click',()=>{box.classList.toggle('hy-ai-open');trigger.classList.toggle('open');trigger.querySelector('b').textContent=box.classList.contains('hy-ai-open')?'סגור כלי AI':'צלם את העבודה עם AI'});box.parentNode.insertBefore(trigger,box)})}
  function enhanceActions(){$$('button').forEach(btn=>{const t=(btn.textContent||'').trim();if(/וואטסאפ|WhatsApp/i.test(t))btn.classList.add('hy-send-main');if(/PDF/i.test(t))btn.classList.add('hy-pdf-action');if(/הוסף.*פריט|פריט חדש/.test(t))btn.classList.add('hy-add-item')})}
  function mobileFocus(){if(innerWidth>860)return;$$('input,select,textarea').forEach(el=>{if(!el.dataset.hyFocus){el.dataset.hyFocus='1';el.addEventListener('focus',()=>setTimeout(()=>el.scrollIntoView({behavior:'smooth',block:'center'}),180))}})}
  function run(){if(busy)return;busy=true;try{normalizeNavigation();hideLegacyInternalCosting();polishAiCopy();addWorkspaceIntro();simplifyChrome();moveCustomerFirst();collapseAiOnMobile();enhanceActions();mobileFocus()}finally{busy=false}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else run();let timer;new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(run,120)}).observe(document.documentElement,{childList:true,subtree:true});
})();
