/* Carpentry Quotes — product architecture v2 */
(function(){
  let busy=false;
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  function clickTab(tab){$('nav.tabs button[data-tab="'+tab+'"]')?.click();window.scrollTo({top:0,behavior:'smooth'})}
  function normalizeNavigation(){const labels={quote:['＋','הצעה'],cutlist:['▦','חיתוך'],orders:['◎','עבודות'],settings:['₪','מחירון']};$$('nav.tabs button[data-tab]').forEach(btn=>{const cfg=labels[btn.dataset.tab];if(!cfg)return;const icon=$('.tab-icon',btn);if(icon)icon.textContent=cfg[0];const spans=$$('span',btn);if(spans.length>1)spans[spans.length-1].textContent=cfg[1]})}
  function addDashboard(){const main=$('main');if(!main||$('#hy-dashboard'))return;const dash=document.createElement('section');dash.id='hy-dashboard';dash.className='hy-dashboard';dash.innerHTML=`<div class="hy-dash-head"><div><span class="hy-eyebrow">סדנת העבודה שלי</span><h2>מה עושים עכשיו?</h2><p>כל פעולה מרכזית במקום אחד.</p></div><button class="primary hy-new-quote" type="button">＋ הצעת מחיר חדשה</button></div><div class="hy-dash-actions"><button type="button" data-go="quote"><b>＋</b><strong>הצעה חדשה</strong><small>לקוח → עבודה → מחיר → שליחה</small></button><button type="button" data-go="orders"><b>◎</b><strong>עבודות ולקוחות</strong><small>הצעות, סטטוס ותשלומים</small></button><button type="button" data-go="settings"><b>₪</b><strong>המחירון שלי</strong><small>מחירי חומרים לפי מ״ר</small></button><button type="button" data-go="cutlist"><b>▦</b><strong>חיתוך</strong><small>מידות ורשימת חלקים לייצור</small></button></div>`;main.insertBefore(dash,main.firstElementChild);$$('[data-go]',dash).forEach(b=>b.addEventListener('click',()=>clickTab(b.dataset.go)));$('.hy-new-quote',dash)?.addEventListener('click',()=>clickTab('quote'));
    const nav=$('nav.tabs');nav?.addEventListener('click',e=>{const b=e.target.closest('button[data-tab]');if(!b)return;dash.classList.toggle('hy-dashboard-hidden',b.dataset.tab!=='quote')});
  }
  function hideLegacyInternalCosting(){const terms=['תכנון','ייצור','תקורה'];$$('label,.field,.row2,.cost-row,.setting-row').forEach(el=>{const txt=(el.textContent||'').trim();if(terms.some(t=>txt.includes(t))){const target=el.matches('label')?(el.closest('.row2')||el.parentElement):el;if(target)target.classList.add('hybrid-hide-cost')}})}
  function polishAiCopy(){$$('.ai-box .hint,.ai-box .warn,.ai-status').forEach(el=>{if((el.textContent||'').includes('דיוק'))el.textContent='ה-AI מציע נתונים ראשוניים. יש לאמת מידות לפני שליחת הצעה.'})}
  function addWorkspaceIntro(){const quote=$('#tab-quote');if(!quote||$('.hy-workspace',quote))return;const hero=document.createElement('section');hero.className='hy-workspace';hero.innerHTML=`<div><span class="hy-eyebrow">יצירת הצעה</span><h2>הצעה מקצועית בחמישה צעדים</h2><p>ממלאים רק מה שצריך. אפשר לחזור ולערוך בכל שלב.</p></div><div class="hy-flow"><span class="active">1 <b>לקוח</b></span><span>2 <b>עבודה</b></span><span>3 <b>פריטים</b></span><span>4 <b>מחיר</b></span><span>5 <b>שליחה</b></span></div>`;quote.insertBefore(hero,quote.firstElementChild)}
  function emphasizeMaterialPricing(){const settingsTab=$('#tab-settings');if(!settingsTab)return;const labels=$$('label',settingsTab);const label=labels.find(l=>/סוגי חומרים.*מחיר למ״ר/.test(l.textContent||''));if(!label||label.dataset.hyPriceReady)return;label.dataset.hyPriceReady='1';label.id='materialPricingSettings';label.style.fontSize='16px';label.style.color='#1e2229';const note=document.createElement('div');note.className='hint';note.textContent='הגדר כאן את המחיר שלך לכל חומר לפי מ״ר. המחיר משמש אוטומטית בכל הצעה.';label.insertAdjacentElement('afterend',note)}
  function simplifyChrome(){const journey=$('.journey');if(journey)journey.classList.add('hy-legacy-journey');const trust=$('.trust-row');if(trust)trust.classList.add('hy-trust');$$('body *').forEach(el=>{const t=(el.textContent||'').trim();if(el.children.length<4&&/מצב מקומי.*Supabase/.test(t))el.classList.add('hy-hide-dev')})}
  function moveCustomerFirst(){const quote=$('#tab-quote');if(!quote||quote.dataset.hyOrdered)return;const customerLabel=$$('label',quote).find(l=>/שם לקוח/.test(l.textContent||''));if(!customerLabel)return;const customerPanel=customerLabel.closest('.panel');const grid=$('.grid2',quote);if(customerPanel&&grid&&customerPanel.parentElement===grid){grid.insertBefore(customerPanel,grid.firstElementChild);customerPanel.classList.add('hy-customer-first');quote.dataset.hyOrdered='1'}}
  function collapseAiOnMobile(){if(innerWidth>860)return;$$('.ai-box').forEach(box=>{if(box.dataset.hyCollapsed)return;box.dataset.hyCollapsed='1';box.classList.add('hy-ai-collapsed');const trigger=document.createElement('button');trigger.type='button';trigger.className='hy-ai-trigger';trigger.innerHTML='<span>📷</span><b>עזרה מ-AI מתמונה</b><small>אופציונלי — אפשר למלא ידנית</small>';trigger.addEventListener('click',()=>{box.classList.toggle('hy-ai-open');trigger.classList.toggle('open')});box.parentNode.insertBefore(trigger,box)})}
  function enhanceActions(){$$('button').forEach(btn=>{const t=(btn.textContent||'').trim();if(/וואטסאפ|WhatsApp/i.test(t))btn.classList.add('hy-send-main');if(/PDF/i.test(t))btn.classList.add('hy-pdf-action')})}
  function mobileFocus(){if(innerWidth>860)return;$$('input,select,textarea').forEach(el=>{if(!el.dataset.hyFocus){el.dataset.hyFocus='1';el.addEventListener('focus',()=>setTimeout(()=>el.scrollIntoView({behavior:'smooth',block:'center'}),180))}})}
  function run(){if(busy)return;busy=true;try{normalizeNavigation();addDashboard();hideLegacyInternalCosting();polishAiCopy();addWorkspaceIntro();emphasizeMaterialPricing();simplifyChrome();moveCustomerFirst();collapseAiOnMobile();enhanceActions();mobileFocus()}finally{busy=false}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else run();let timer;new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(run,150)}).observe(document.documentElement,{childList:true,subtree:true});
})();