/* Quote Wizard V2 — mobile-first, preserves existing form logic */
(function(){
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  let step=1;
  const names=['לקוח','עבודה','פריטים','מחיר','שליחה'];
  function quote(){return $('#tab-quote')}
  function fieldWrap(label){const body=label.closest('.panel-body');if(!body)return label.parentElement;let n=label;while(n.parentElement&&n.parentElement!==body)n=n.parentElement;return n}
  function tagFields(){const q=quote();if(!q||q.dataset.wizardTagged)return;q.dataset.wizardTagged='1';$$('label',q).forEach(l=>{const t=(l.textContent||'').trim();let s=0;if(/שם לקוח|טלפון לקוח/.test(t))s=1;else if(/תיאור הפרויקט/.test(t))s=2;else if(/סוג חומר|שטח חומר|תוספות|פרזול|עבודה|התקנה/.test(t))s=3;if(s){const w=fieldWrap(l);if(w&&!w.dataset.hyStep)w.dataset.hyStep=String(s)}});$$('.ai-box,.hy-ai-trigger',q).forEach(x=>x.dataset.hyStep='2');const panels=$$('.grid2 > .panel',q);if(panels[1])panels[1].classList.add('hy-preview-panel');$$('.actions-row',q).forEach(x=>x.classList.add('hy-send-actions'))}
  function ensureAiAccess(){const q=quote(),box=$('#aiBoxQ',q),input=$('#aiImageInputQ',q);if(!q||!box||!input||$('.hy-ai-quote-entry',q))return;const entry=document.createElement('div');entry.className='hy-ai-quote-entry';entry.dataset.hyStep='1';entry.innerHTML='<label for="aiImageInputQ" class="hy-ai-photo-btn" role="button" tabindex="0"><span>📷</span><b>צלם או העלה תמונה ל-AI</b><small>ה-AI יציע שטח חומר משוער וניתן לתקן ידנית</small></label>';box.parentNode.insertBefore(entry,box);const picker=$('.hy-ai-photo-btn',entry);picker.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();input.click()}});input.addEventListener('change',()=>{if(!input.files||!input.files.length)return;setStep(2);box.classList.add('hy-ai-open');box.classList.remove('hy-ai-collapsed');const legacy=$('.hy-ai-trigger',q);if(legacy)legacy.style.display='none';setTimeout(()=>box.scrollIntoView({behavior:'smooth',block:'center'}),120)})}
  function addControls(){const q=quote();if(!q||$('#hy-wizard-controls'))return;const c=document.createElement('div');c.id='hy-wizard-controls';c.className='hy-wizard-controls no-print';c.innerHTML='<button type="button" class="secondary" data-prev>חזרה</button><div><strong data-title>לקוח</strong><small data-save>טיוטה נשמרת אוטומטית</small></div><button type="button" class="primary" data-next>המשך</button>';q.appendChild(c);$('[data-prev]',c).onclick=()=>setStep(step-1);$('[data-next]',c).onclick=()=>setStep(step+1);$$('.hy-flow span',q).forEach((x,i)=>{x.style.cursor='pointer';x.onclick=()=>setStep(i+1)})}
  function setStep(n){step=Math.max(1,Math.min(5,n));const q=quote();if(!q)return;q.dataset.wizardStep=String(step);$$('.hy-flow span',q).forEach((x,i)=>x.classList.toggle('active',i===step-1));$$('[data-hy-step]',q).forEach(x=>x.classList.toggle('hy-step-hidden',Number(x.dataset.hyStep)!==step));const preview=$('.hy-preview-panel',q),actions=$$('.hy-send-actions',q);if(preview)preview.classList.toggle('hy-step-hidden',step<4);actions.forEach(a=>a.classList.toggle('hy-step-hidden',step!==5));const c=$('#hy-wizard-controls');if(c){$('[data-title]',c).textContent='שלב '+step+' — '+names[step-1];$('[data-prev]',c).style.visibility=step===1?'hidden':'visible';$('[data-next]',c).textContent=step===5?'סיום':'המשך';$('[data-next]',c).onclick=step===5?()=>document.querySelector('nav.tabs button[data-hy-home]')?.click():()=>setStep(step+1)}$('.hy-workspace',q)?.scrollIntoView({behavior:'smooth',block:'start'})}
  window.hySetQuoteStep=setStep;
  function autosave(){const q=quote();if(!q||q.dataset.draftReady)return;q.dataset.draftReady='1';const key='carpentry_quote_draft_v2';try{const d=JSON.parse(localStorage.getItem(key)||'{}');$$('input[id],select[id],textarea[id]',q).forEach(el=>{if(d[el.id]!=null&&!el.value){el.value=d[el.id];el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}))}})}catch(e){}let timer;q.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>{const d={};$$('input[id],select[id],textarea[id]',q).forEach(el=>{if(el.type!=='file')d[el.id]=el.value});try{localStorage.setItem(key,JSON.stringify(d));const s=$('[data-save]');if(s)s.textContent='נשמר עכשיו ✓'}catch(e){}},350)})}
  function init(){const q=quote();if(!q)return;tagFields();ensureAiAccess();addControls();autosave();setStep(1)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,300));else setTimeout(init,300);
})();
